plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.devendra'
version = '1.0.0'
base { archivesName = 'SlenderManDirector-Forge-1.20.1' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

repositories { mavenCentral() }

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.20'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [version: project.version]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) { expand replaceProperties + [project: project] }
}
