modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="slenderman_director"
version="${version}"
displayName="Slender Man Director"
description='''Standalone cinematic Slender Man director mod for Forge 1.20.1.'''

[[dependencies.slenderman_director]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.slenderman_director]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
