plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'Train31Director-Forge-1.20.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                train31 { source sourceSets.main }
            }
        }
        server {
            workingDirectory project.file('run-server')
            property 'forge.logging.console.level', 'info'
            args '--nogui'
            mods {
                train31 { source sourceSets.main }
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
        minecraft_version: minecraft_version,
        forge_version: forge_version,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_version: mod_version
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : mod_name,
            'Specification-Vendor'    : 'Injaa',
            'Specification-Version'   : mod_version,
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : archiveVersion,
            'Implementation-Vendor'   : 'Injaa'
        ])
    }
    finalizedBy 'reobfJar'
}
