modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="remotehide"
version="${version}"
displayName="Remote Hide Addon"
description='''Hides Light Director and Horror Director remotes while held for cinematic recording.'''

[[dependencies.remotehide]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.remotehide]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
