plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.38'
}

group = 'com.devendra'
version = '1.0.1'
base { archivesName = 'RemoteHideAddon-Forge-1.20.1' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

repositories { mavenCentral() }

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.20'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, 'remotehide.refmap.json'
    config 'remotehide.mixins.json'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [version: project.version]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) { expand replaceProperties + [project: project] }
}

jar {
    manifest {
        attributes([
            'Specification-Title': 'Remote Hide Addon',
            'Specification-Vendor': 'Devendra',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor': 'Devendra',
            'MixinConfigs': 'remotehide.mixins.json'
        ])
    }
}
